server:
  port: 8082
spring:
  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
#            allow all
#            allowedOrigins: "*"
            allowedOrigins: "http://localhost:8081"
#            allow all
#            allowedMethods: "*"
            allowedMethods:
              - GET
              - POST
            allowed-headers: "*"
        add-to-simple-url-handler-mapping: true

      routes:
        - id: users-status-check
#          uri: http://localhost:8081
          uri: lb://resource-service
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: lb://albums-service
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: lb://photos-service
          predicates:
            - Path=/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/