server:
  port: 8000


#localhost:8000/oauth2/authorize?response_type=code&client_id=client1&redirect_uri=http://127.0.0.1:8080/authorized&scope=openid read

#curl --location 'localhost:8000/oauth2/token' \
#--header 'Authorization: Basic Y2xpZW50MTpteUNsaWVudFNlY3JldFZhbHVl' \
#--header 'Content-Type: application/x-www-form-urlencoded' \
#--header 'Cookie: JSESSIONID=89FBEA29277F742667CA8B3A9D7FC627' \
#--data-urlencode 'grant_type=authorization_code' \
#--data-urlencode 'code=FTiUWfXA6vrb0jDAB7NPNrck2c4l0xQM-EayASiyYrRPB15lCjzc6ByDJCxRIQt78zlGiKvig887TXFQqm28L2AdatcfqY23QK6NkihuBzI_ncBd3Ii13ntRrG2XwyGX' \
#--data-urlencode 'redirect_uri=http://127.0.0.1:8080/authorized'