server:
  port: 8000


#localhost:8000/oauth2/authorize?response_type=code&client_id=client1&redirect_uri=http://127.0.0.1:8080/authorized&scope=openid read

curl --location 'localhost:8000/oauth2/token' \
--header 'Authorization: Basic Y2xpZW50MTpteUNsaWVudFNlY3JldFZhbHVl' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: JSESSIONID=89FBEA29277F742667CA8B3A9D7FC627' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code=3DhlvJr1YlSpQX6nc0YLxMq1Bw32oFt2dAPlqgYW8olNEvJpp5IojnbFOgs-2IkKKlFX2j7JTOJYE-e1wq6U5CRw5kUhFfgI-ZxD48MYO0-0wgGlAjM6mZl_Znii5TTB' \
--data-urlencode 'redirect_uri=http://127.0.0.1:8080/authorized'